import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { motion } from "framer-motion";
import Navbar from "../components/Navbar";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex flex-col min-h-screen bg-[#050a12] p-10 items-center relative">
        <Intro />
        <button className="absolute bottom-8 p-4 bg-white/[0.05] rounded-md">
          More about me
        </button>
      </main>
      <div className="h-[1500px]">Demo</div>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

function Intro() {
  return (
    <div className="flex flex-col px-40 mt-40 w-full mb-20">
      <motion.h2
        initial={{ y: -40, opacity: 0 }}
        animate={{ y: 0, opacity: 0.6 }}
        transition={{
          y: {
            type: "easeIn",
            stiffness: 80,
            duration: 0.5,
          },
          opacity: {
            type: "easeIn",
            duration: 0.7,
          },
        }}
        className="text-xl my-2 ml-1 opacity-60"
      >
        Welcome to my Portfolio, I'm
      </motion.h2>
      <motion.h1
        initial={{ x: 90, opacity: 0 }}
        animate={{ x: 0, opacity: 1 }}
        transition={{
          delay: 0.2,
          x: {
            type: "spring",
            stiffness: 40,
            duration: 0.5,
          },
          opacity: {
            type: "easeIn",
            duration: 0.7,
          },
        }}
        className="text-white text-6xl my-2 font-bold text-transparent text-8xl bg-clip-text w-fit bg-gradient-to-r from-emerald-400 to-teal-700 drop-shadow-[10px_20px_20px_rgba(44,191,144,0.1)]"
      >
        Nathan Pho,
      </motion.h1>
      <motion.h1
        initial={{ x: -90, opacity: 0 }}
        animate={{ x: 0, opacity: 1 }}
        transition={{
          delay: 0.2,
          x: {
            type: "spring",
            stiffness: 40,
            duration: 0.5,
          },
          opacity: {
            type: "easeIn",
            duration: 0.7,
          },
        }}
        className="text-6xl my-2"
      >
        Full-Stack Developer & Designer.
      </motion.h1>
      <motion.div
        initial={{ y: 40, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{
          delay: 0.6,
          y: {
            type: "easeIn",
            stiffness: 80,
            duration: 0.5,
          },
          opacity: {
            type: "easeIn",
            duration: 0.7,
          },
        }}
        className="w-[600px] my-2"
      >
        <h2 className="text-xl my-2 ml-1 opacity-60">
          I am a full-stack JavaScript developer a passion for creating highly
          functional, responsive, and beautiful applications for the web and
          mobile.
        </h2>
        <motion.button
          style={{ backgroundSize: "200%", backgroundPositionX: "50%" }}
          whileTap={{ scale: 0.98 }}
          whileHover={{
            backgroundPositionX: "10%",
            transition: { type: "easeInOut" },
          }}
          className="w-fit px-4 py-3 text-lg bg-gradient-to-r  from-cyan-700 via-emerald-500 to-teal-600 w-fit rounded-md my-6"
        >
          Get in touch
        </motion.button>
      </motion.div>
    </div>
  );
}
